config/routes.rb
Rails.application.routes.draw do
  resources :kanbans
  patch '/kanbans/:id/sort', to: 'kanbans#sort', as: "kanban_sort"
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :kanban_column
end

app/models/kanban.rb
class Kanban < ApplicationRecord
  has_many :kanban_columns
  has_many :cards, through: :kanban_columns
end

app/models/kanban_column.rb
class KanbanColumn < ApplicationRecord
  belongs_to :kanban
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kanbans_controller.rb
class KanbansController < ApplicationController
  before_action :set_kanban, only: [:show, :edit, :update, :destroy, :sort]

  # GET /kanbans
  # GET /kanbans.json
  def index
    @kanbans = Kanban.all
  end

  # GET /kanbans/1
  # GET /kanbans/1.json
  def show
  end

  # GET /kanbans/new
  def new
    @kanban = Kanban.new
  end

  # GET /kanbans/1/edit
  def edit
  end

  # POST /kanbans
  # POST /kanbans.json
  def create
    @kanban = Kanban.new(kanban_params)

    respond_to do |format|
      if @kanban.save
        format.html { redirect_to @kanban, notice: 'Kanban was successfully created.' }
        format.json { render :show, status: :created, location: @kanban }
      else
        format.html { render :new }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kanbans/1
  # PATCH/PUT /kanbans/1.json
  def update
    respond_to do |format|
      if @kanban.update(kanban_params)
        format.html { redirect_to @kanban, notice: 'Kanban was successfully updated.' }
        format.json { render :show, status: :ok, location: @kanban }
      else
        format.html { render :edit }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  def sort
    # Get the new col sort
    sorted_cols = JSON.parse(kanban_params["kanbanIds"])["columns"]
    sorted_cols.each do |col|
      # Look at each of its cards
      col["itemIds"].each do |card_id|
        # Find the card if in the DB and update its column and position within the column
        Card.find(card_id).update(
          kanban_column: KanbanColumn.find(col["id"]),
          position: col["itemIds"].find_index(card_id)
        )
      end
    end
  end

  # DELETE /kanbans/1
  # DELETE /kanbans/1.json
  def destroy
    @kanban.destroy
    respond_to do |format|
      format.html { redirect_to kanbans_url, notice: 'Kanban was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kanban
      @kanban = Kanban.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kanban_params
      params.require(:kanban).permit(:name, :description, :kanbanIds)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kanbans/_form.html.erb
<%= simple_form_for(@kanban) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :cards %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/kanbans/edit.html.erb
<h1>Editing Kanban</h1>

<%= render 'form', kanban: @kanban %>

<%= link_to 'Show', @kanban %> |
<%= link_to 'Back', kanbans_path %>

app/views/kanbans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kanbans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Cards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kanbans.each do |kanban| %>
      <tr>
        <td><%= kanban.name %></td>
        <td><%= kanban.description %></td>
        <td><%= link_to 'Show', kanban %></td>
        <td><%= link_to 'Edit', edit_kanban_path(kanban) %></td>
        <td><%= link_to 'Destroy', kanban, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kanban', new_kanban_path %>

app/views/kanbans/new.html.erb
<h1>New Kanban</h1>

<%= render 'form', kanban: @kanban %>

<%= link_to 'Back', kanbans_path %>

app/views/kanbans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kanban.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @kanban.description %>
</p>

<% if false %>
  <%= form_with url: kanban_sort_path, method: :patch do |f|%>
    <%= f.text_field 'kanban[kanbanIds]', class: "kanban-form-input" %>
    <%= f.submit "Saved changes" %>
  <% end %>
<% end %>

<div class="kanban" data-id="<%= @kanban.id %>">
  <% @kanban.kanban_columns.each do |column| %>
    <ul class="kanban-col" data-col-id=<%= column.id %> >
      <li class="kanban-col-name"><%= column.name %></li>
      <% column.cards.sort_by{ |card| card.position}.each do |item| %>
        <li class="kanban-col-item" data-item-id=<%= item.id %> >
          <%= item.content %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>


<%= link_to 'Edit', edit_kanban_path(@kanban) %> |
<%= link_to 'Back', kanbans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DragndropKanbanApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>